# Generated by Django 4.2.7 on 2023-12-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOfferCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(upload_to='section_offer_card_images/')),
            ],
        ),
    ]
