# Generated by Django 4.2.7 on 2023-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sectionhotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightsSectionCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('next_flight', models.IntegerField()),
                ('image', models.ImageField(upload_to='section_flights_images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
