# Generated by Django 4.2.7 on 2023-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_branchoffices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('medal_image', models.ImageField(upload_to='section_assistance_images/')),
                ('time', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50)),
                ('queries', models.CharField(max_length=50)),
                ('internation', models.CharField(max_length=50)),
                ('reinstatement', models.CharField(max_length=50)),
                ('medicaments', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
    ]
